### ISSUE TITLE
RGB LED Handler

### ISSUE THREAD

**Issue by Sothus** [Sothus/SmartPiHome#2]
Issue based on [Project plans](https://github.com/Sothus/SmartPiHome/wiki/Project-plans#rgb-led-handler).

Objective is to create a script with class which can control RGB LED.
Each color should be able to set by PWM

**Comment by Schmen** [comment]
There are a lot of information about RGB and others helpfull stuff: https://github.com/sunfounder/Sunfounder_SuperKit_Python_code_for_RaspberryPi

**Comment by Schmen** [comment]
Create new script using library pigpio.
